### ISSUE TITLE
bootloop problems

### ISSUE THREAD

**Issue by decaduto** [manikantaraavi/kernel_oneplus_sm7250#2]
Sorry if I disturb,
I tried to boot the new boot.img with the compiled Image, using android_boot_image_editor, this results in the following error:
```
the current image(boot/recovery) have been destroyed and can not boot.
ecc..
```

Do you know if this kernel is compatible with android 12? does it require a custom boot.img? which tools do you use for booting it?
Regards.

**Comment by manikantaraavi** [comment]
> you know if this kernel is compatible with android 12? does it require a custom boot.img? which tools do

Seems to be fine here it even boots on A13 and built and booted just now without any changes
Just clone and do ./build.sh 
Let me know which from u are trying to boot it
<img width="853" alt="image" src="https://user-images.githubusercontent.com/46994003/192125796-5d646307-a4e1-40a0-919b-b5461711371d.png">

**Comment by Prashant1873** [comment]
Extract image from released kernel on telegram and make boot image if you want.

**Comment by decaduto** [comment]
> > you know if this kernel is compatible with android 12? does it require a custom boot.img? which tools do
> 
> Seems to be fine here it even boots on A13 and built and booted just now without any changes Just clone and do ./build.sh Let me know which from u are trying to boot it <img alt="image" width="853" src="https://user-images.githubusercontent.com/46994003/192125796-5d646307-a4e1-40a0-919b-b5461711371d.png">

problem resolved, now the phone is bricked forever... flashed the entire OxygenOs iso which seemed compatible with my build version... the result is that it cannot be even powered on, obv is impossible to enter in fastboot or similar, suspect that the sbl/xbl has been completely overwritten.

**Comment by Prashant1873** [comment]
1) anykernel zip is supposed to be flashed, no need to make boot.img
2) what's the point of compiling already released kernel
3) flash stock through download mode using pc ig it should boot

**Comment by Prashant1873** [comment]
> > > you know if this kernel is compatible with android 12? does it require a custom boot.img? which tools do
> > 
> > 
> > Seems to be fine here it even boots on A13 and built and booted just now without any changes Just clone and do ./build.sh Let me know which from u are trying to boot it <img alt="image" width="853" src="https://user-images.githubusercontent.com/46994003/192125796-5d646307-a4e1-40a0-919b-b5461711371d.png">
> 
> problem resolved, now the phone is bricked forever... flashed the entire OxygenOs iso which seemed compatible with my build version... the result is that it cannot be even powered on, obv is impossible to enter in fastboot or similar, suspect that the sbl/xbl has been completely overwritten.


anykernel zip is supposed to be flashed, no need to make boot.img
what's the point of compiling already released kernel
flash stock through download mode using pc ig it should boot
